/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Scaffold.Api | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * Validation errors grouped by field name.
 */
export type ProblemDetailsErrors = { [key: string]: string[] };
