/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Scaffold.Api | v1
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";
import { customInstance } from ".././axios-instance";
import type { WeatherForecast } from "../models";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getWeatherForecast = (
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<WeatherForecast[]>(
		{ url: `/api/weatherforecast`, method: "GET", signal },
		options,
	);
};

export const getGetWeatherForecastQueryKey = () => {
	return [`/api/weatherforecast`] as const;
};

export const getGetWeatherForecastQueryOptions = <
	TData = Awaited<ReturnType<typeof getWeatherForecast>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getWeatherForecast>>,
			TError,
			TData
		>
	>;
	request?: SecondParameter<typeof customInstance>;
}) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetWeatherForecastQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getWeatherForecast>>
	> = ({ signal }) => getWeatherForecast(requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getWeatherForecast>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWeatherForecastQueryResult = NonNullable<
	Awaited<ReturnType<typeof getWeatherForecast>>
>;
export type GetWeatherForecastQueryError = unknown;

export function useGetWeatherForecast<
	TData = Awaited<ReturnType<typeof getWeatherForecast>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getWeatherForecast>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getWeatherForecast>>,
					TError,
					Awaited<ReturnType<typeof getWeatherForecast>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWeatherForecast<
	TData = Awaited<ReturnType<typeof getWeatherForecast>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getWeatherForecast>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getWeatherForecast>>,
					TError,
					Awaited<ReturnType<typeof getWeatherForecast>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWeatherForecast<
	TData = Awaited<ReturnType<typeof getWeatherForecast>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getWeatherForecast>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetWeatherForecast<
	TData = Awaited<ReturnType<typeof getWeatherForecast>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getWeatherForecast>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetWeatherForecastQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return { ...query, queryKey: queryOptions.queryKey };
}
